---
##########################
## Hadolint config file ##
##########################
ignored:
  - DL3018 # We do pin version in pipfile.lock
  - DL3013 # We do pin version in pipfile.lock
  - DL3003 # Ignore workdir so we don't add layers
