name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          webhook_production: http://127.0.0.1
          verbose: true
          silent: false

      - name: Print Output
        run: echo "${{ steps.test-action.outputs.response-body }}"

      - name: Test second Local Action
        id: test-action-2
        uses: ./
        with:
          webhook_production: http://prod.localhost
          webhook_release: http://release.localhost
          verbose: true
          silent: false

      - name: Print Output
        run: echo "${{ steps.test-action-2.outputs.response-body }}"

      - name: Test second Local Action
        uses: ./
        with:
          webhook_production: http://prod.localhost
